<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>simple php app</title>
    <link rel="stylesheet" type="text/css" href="style.css">
</head>

<body>
    <p>Welcome to the world of <strong>PHP, XML, CSS and PHTML</strong>.</p>

    <p>Book Club Terminal : Circa 1984</p>
    <!-- Links basic.php file with phtml file -->
    <?php include "basic.php"; ?>

</body>

</html>